### ISSUE TITLE
I have issue with this loader

### ISSUE THREAD

**Issue by jinkwon** [bestander/html-minify-loader#1]
Hi,
I have issue with this loader.
Could you please give me some advice?
Did I set up wrong??

Thanks.

setting

``` javascript
module: { loaders: [ { test: /\.html$/, name: 'mandrillTemplates', loader: 'raw:html-minify' } ] }
```

source.js

``` javascript
'error_message.html': require('./template/error_message.html')
```

Will return 
Module not found: Error: Cannot resolve module 'raw:html-minify' in

**Comment by bestander** [comment]
Jey @Jinkwon, I reckon you need to do 'raw!html-minify', not 'raw:html-minify'.
`!` is the separator for loaders in webpack

**Comment by bestander** [comment]
Reopen issue if it is still relevant
