### ISSUE TITLE
Webpack v4 Support

### ISSUE THREAD

**Issue by meseras** [bestander/html-minify-loader#10]
Any chance you are working on an upgrade to support webpack v4.

**Comment by bestander** [comment]
Hey, I haven’t been using this plugin for a long time.
Will gladly merge a PR if you send one

**Comment by hswami** [comment]
I have a fix to support webpack v4 while maintaining compatibility with older versions. I can't send a PR because I can't publish a new branch. Can you add me as a contributor?

**Comment by bestander** [comment]
Of course I can.
But why can't you send a PR from your clone?

**Comment by hswami** [comment]
Done. It was a simple change ... replaced `this.options['html-minify-loader']` with `(this.options && this.options['html-minify-loader'])` to ensure it works with webpack v4 while maintaining backward compatibility with older versions.

**Comment by bestander** [comment]
fixed via https://github.com/bestander/html-minify-loader/pull/11
