### ISSUE TITLE
Shouldn't loader-utils be in dependencies?

### ISSUE THREAD

**Issue by briced** [bestander/html-minify-loader#8]
When updating from 1.1.0 to 1.2.0, my build stopped working. Upon inspection, I see that the loader-utils in my dependencies is 0.2.16 (indirect dependency, I didn't put a version in my package.json)
After, editing html-minify-loader to move loader-utils in dependencies, npm (3) use [its dependency resolution logic](https://docs.npmjs.com/how-npm-works/npm3) and add a node_modules inside html-minify-loader folder, with the wanted loader-utils dependency, and everything works again.

As I see it, loader-utils is needed for html-minify-loader, so it should be in dependencies, not in devDependencies.
What do you think?

**Comment by netmindr** [comment]
You may have another dependency that requires loader-utils be in 'dependencies'. Since we did not have an existing dependency on it, putting it in devDependencies worked - YMMV.
I spoke to @bestander about it and agreed that moving it up into dependencies is not an issue.

**Comment by briced** [comment]
PR created #9

**Comment by bestander** [comment]
Sorry for breaking, PR merged and published to npm.
